gedaiu/fluent-asserts

core/fluentasserts/core/array.d
core/fluentasserts/core/callable.d

fix range asserts

---

.travis.yml
api/ranges.md
core/fluentasserts/core/array.d
core/fluentasserts/core/base.d
core/fluentasserts/core/basetype.d
core/fluentasserts/core/callable.d
core/fluentasserts/core/objects.d
core/fluentasserts/core/results.d
core/fluentasserts/core/string.d
travis-ci.sh

10 contain only

---

README.md
api/callable.md
core/fluentasserts/core/base.d
core/fluentasserts/core/basetype.d
core/fluentasserts/core/callable.d

9 function execution time

---

api/callable.md
core/fluentasserts/core/base.d
core/fluentasserts/core/callable.d

8 exception messages

---

core/fluentasserts/core/basetype.d

fix interval assertion messages

---

core/fluentasserts/core/array.d

fix ListComparison to work with structs and classes

---

core/fluentasserts/core/array.d

Reverts gedaiu/fluent-asserts#24

Revert "fix ListComparison to work with structs and classes"

---

.travis.yml
api/callable.md
core/fluentasserts/core/base.d
core/fluentasserts/core/callable.d
core/fluentasserts/core/results.d

50 be null for delegate

---

core/fluentasserts/core/results.d

remove spaces between words

---

core/fluentasserts/core/array.d
core/fluentasserts/core/string.d

allow const and immutable comparisons

---

api/objects.md
core/fluentasserts/core/objects.d

39 comparable objects

---

api/callable.md
core/fluentasserts/core/array.d
core/fluentasserts/core/base.d
core/fluentasserts/core/basetype.d
core/fluentasserts/core/callable.d
core/fluentasserts/core/objects.d
core/fluentasserts/core/string.d

38 throw exception

---

core/fluentasserts/core/objects.d

add interface test

---

core/fluentasserts/core/base.d
core/fluentasserts/core/basetype.d

evaluate const values

---

core/fluentasserts/core/basetype.d
core/fluentasserts/core/callable.d
core/fluentasserts/core/results.d
test/values.d

37 wrong code sugestion

---

core/fluentasserts/core/array.d
core/fluentasserts/core/callable.d

52 void array compare

---

core/fluentasserts/core/results.d
test/values.d

better source handeling

---

core/fluentasserts/core/base.d
core/fluentasserts/core/callable.d
core/fluentasserts/core/results.d

move source result init in Result struct

---

core/fluentasserts/core/objects.d

59 fix null comparison

---

core/fluentasserts/core/results.d
test/class.d

fix method source

---

core/fluentasserts/core/base.d
core/fluentasserts/core/callable.d

add with message string parameter

---

api/ranges.md
core/fluentasserts/core/array.d

31 approximately for ranges

---

core/fluentasserts/core/array.d
core/fluentasserts/core/base.d
core/fluentasserts/core/basetype.d
core/fluentasserts/core/callable.d
core/fluentasserts/core/objects.d
core/fluentasserts/core/results.d
core/fluentasserts/core/string.d
vibe/fluentasserts/vibe/json.d
vibe/fluentasserts/vibe/request.d

I've added the `@safe` annotation for everything in order to solve #73.
Things that weren't safe I annotated with `@trusted` or in rare cases changed the unsafe code to safe code.

@safe'd everything

---

.gitignore
.travis.yml
dub.json
source/fluentasserts/vibe/json.d
source/fluentasserts/vibe/request.d
test/vibe-0.7/dub.json
test/vibe-0.7/source/app.d
test/vibe-0.8/dub.json
test/vibe-0.8/source/app.d
travis-ci.sh

add vibe exemple projects
